### ISSUE TITLE
Incorrect ViT MAE Implementation

### ISSUE THREAD

**Issue by LokeshBadisa** [jiaminchen-1031/transformerinterp#1]
In ViT MAE implementation, `timm` applies `mean` and then `fc_norm` but the implementation here seems to be `fc_norm` and then `mean` i.e. order of applying them has been changed. Let me know if I'm wrong. If not, please correct it.

**Comment by jiaminchen-1031** [comment]
Hi,

yes, we have checked with the official implementation and what you mentioned is right. The code has been corrected.

Thanks for letting us know !

Best,
